# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    Symfony\Component\PasswordHasher\Hasher\NativePasswordHasher:
        autowire: true

    symfony_services:
        namespace: App\
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
        tags: [ symfony_services ]

    domain_services:
        namespace: Domain\
        resource: '../Domain/src/'
        exclude:
            - '../Domain/src/UseCase/{AuthenticationPresenter, AuthenticationRequest, AuthenticationResponse}'
            - '../Domain/src/Entity/'
            - '../Domain/src/Security/'
            - '../Domain/src/Gateway/'
        tags: [ domain_services ]


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Auth Decorator to authenticate users on swagger ui
    App\OpenApi\JwtAuthDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments: [ '@.inner' ]

    App\EventListener\JWT\AuthenticationFailure:
        tags:
            -
                name: kernel.event_listener
                event: lexik_jwt_authentication.on_authentication_failure
                method: onAuthenticationFailureResponse

